language: node_js
node_js:
  - stable
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
 - yarn --registry https://registry.npmjs.org/
 - yarn run build
